name: Build and Push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API Server Docker Image
      uses: docker/build-push-action@v2
      with:
        context: src/api
        file: ./src/api/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/mixpeek-api:latest

    - name: Build and push Services Docker Image 
      uses: docker/build-push-action@v2
      with:
        context: src/services
        file: ./src/services/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/mixpeek-services:latest
